config/routes.rb
Stickyapp::Application.routes.draw do
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dynamic Task Manager</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "style", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="main">
<%= yield %>
</div>
		
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_area :task, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br />
    <%= f.text_field :assigned_to %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :level_of_effort %><br />
    <%= f.text_field :level_of_effort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>



<div id="header">
  <h1>Dynamic Task Manager</h1>

  <h2>Create tasks and track their progress</h2>
</div>

  <hr id="header_stripe"/>
  <div id="page_container">
  <div id="toppanel">
    <div id="panel">
    <div id="panel_contents"> </div>


      <h1>Task Generator</h1>
      <h2> Assign tasks to team members</h2>   
      <div class="border" id="login">
      <form id="taskGen">
		<ul class="taskForm">
      		<li>
				<label for="task">Task:</label>
				<input id="task" name="task" type="text" placeholder="Type task here"></input></li> <!--autofocus???-->
			<li>
				<label for="assignedTo">Assigned To:</label>
				<input id="assignedTo" name="assignedTo" type="text" placeholder="Jane Smith"></input></li>			
			<li>
				<label for="datetime">Start Date:</label>
				<input id="datetime" name="datetime" type="date"></input></li>			
			<li>
				<label for="taskNotes">Task Notes:</label>
				<input id="taskNotes" name="taskNotes" type="text" placeholder="Task description..."></input></li>
	        <li>
	        	<label for="priorityLevel">Priority:</label>

					<select id="priorityLevel" name="priorityLevel">
					  <option value ="1">1</option>
					  <option value ="2">2</option>
					  <option value ="3">3</option>
					  <option value ="5">5</option>
					  <option value ="8">8</option>
					  <option value ="13">13</option>
					  <option value ="20">20</option>
					</select>

	</li>
			<li>
		        <label for="loe">Level Of Effort:</label>

					<select id="loe" name="loe">
						  <option value ="low">Low</option>
						  <option value ="medium">Medium</option>
						  <option value ="high">High</option>
					</select></li>
					
            <li><input type="submit" value="Submit"/></li>
        </ul>
        </form>
      </div>
      
    </div>
    <div class="panel_button" style="display: visible;"><img src="images/expand.png"  alt="expand"/> <a href="#">Add Task</a> </div>
    <div class="panel_button" id="hide_button" style="display: none;"><img src="images/collapse.png" alt="collapse" /> <a href="#">Hide</a> </div>

  </div>
  
  <div id="content">
    <p></p>
    
     <form>
            <fieldset>
                <legend>Project Tasks</legend> 

                <p>This is a test to see if i can replicate the task boards at work.</p>


		<div class="taskTable">
			<div id="notStarted" class="column"> 
				<h1>Not Started</h1> 
				<div class="help">Drag a task from this list to place in queue, progress, or completed.</div> 
			</div>
			<div id="inQueue" class="column "> <h1>In Queue</h1> <div class="help">Dragging a task from here to place in progress or completed.</div> </div>
			<div id="inProgress" class="column"> <h1>In Progress</h1> <div class="help">Drag a task to completed once the work for this task has been reviewed and accepted.</div> </div>
			<div id="completed" class="column"> <h1>Completed</h1> <div class="help">Congrats! This stuff is done!</div> </div>
			<div style="clear: both;"></div>
		</div>


            </fieldset>
        </form>
		<br />
		
		<label for="query">Search Tasks</label>
		<input id="query" name="query" type="search" placeholder="search the app!"></input>
    
    
  </div>
  <div id="footer">
    <p>A work in progress...</p>
    
 
  </div>
</div>




<table>
  <tr>
    <th>Task</th>
    <th>Assigned to</th>
    <th>Due date</th>
    <th>Priority</th>
    <th>Level of effort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.task %></td>
    <td><%= task.assigned_to %></td>
    <td><%= task.due_date %></td>
    <td><%= task.priority %></td>
    <td><%= task.level_of_effort %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @task.task %>
</p>

<p>
  <b>Assigned to:</b>
  <%= @task.assigned_to %>
</p>

<p>
  <b>Due date:</b>
  <%= @task.due_date %>
</p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Level of effort:</b>
  <%= @task.level_of_effort %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>